
import "./globals.css";
import "../css/Responsive.css";
import { ThemeProvider } from "../../tailwind_mui_components.js";
import { Quicksand } from "next/font/google";
import SessionWrapper from "@/components/SessionWrapper";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Pawfinity - The Pet Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={quicksand.className}>
          <ThemeProvider>
            {children}
          </ThemeProvider>
          <script src="https://accounts.google.com/gsi/client" async></script>
        </body>
      </html>
    </SessionWrapper>
  );
}
